version: '3.8'

services:
  web:
    container_name: dev_backend
    build: ../web-project-backend
    env_file: ../web-project-backend/dev.env
    ports:
      - 8000:8000
    command: gunicorn products_aggregator_project.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: dev_db
    env_file: ../web-project-backend/dev.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - static_volume:/web-project-backend/staticfiles/
    restart: always

  nginx:
    container_name: dev_web
    build: ../web-project-frontend
    ports:
      - 80:80
    volumes:
      - ./nginx/development:/etc/nginx/conf.d
      - static_volume:/web-project-backend/staticfiles/
    restart: always
    depends_on:
      - web

volumes:
  static_volume: